// Code generated by Kitex v0.4.2. DO NOT EDIT.

package raft_operations

import (
	api "ClyMQ/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return raft_OperationsServiceInfo
}

var raft_OperationsServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Raft_Operations"
	handlerType := (*api.Raft_Operations)(nil)
	methods := map[string]kitex.MethodInfo{
		"RequestVote":   kitex.NewMethodInfo(requestVoteHandler, newRaft_OperationsRequestVoteArgs, newRaft_OperationsRequestVoteResult, false),
		"AppendEntries": kitex.NewMethodInfo(appendEntriesHandler, newRaft_OperationsAppendEntriesArgs, newRaft_OperationsAppendEntriesResult, false),
		"SnapShot":      kitex.NewMethodInfo(snapShotHandler, newRaft_OperationsSnapShotArgs, newRaft_OperationsSnapShotResult, false),
		"pingpongtest":  kitex.NewMethodInfo(pingpongtestHandler, newRaft_OperationsPingpongtestArgs, newRaft_OperationsPingpongtestResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.2",
		Extra:           extra,
	}
	return svcInfo
}

func requestVoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.Raft_OperationsRequestVoteArgs)
	realResult := result.(*api.Raft_OperationsRequestVoteResult)
	success, err := handler.(api.Raft_Operations).RequestVote(ctx, realArg.Rep)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRaft_OperationsRequestVoteArgs() interface{} {
	return api.NewRaft_OperationsRequestVoteArgs()
}

func newRaft_OperationsRequestVoteResult() interface{} {
	return api.NewRaft_OperationsRequestVoteResult()
}

func appendEntriesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.Raft_OperationsAppendEntriesArgs)
	realResult := result.(*api.Raft_OperationsAppendEntriesResult)
	success, err := handler.(api.Raft_Operations).AppendEntries(ctx, realArg.Rep)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRaft_OperationsAppendEntriesArgs() interface{} {
	return api.NewRaft_OperationsAppendEntriesArgs()
}

func newRaft_OperationsAppendEntriesResult() interface{} {
	return api.NewRaft_OperationsAppendEntriesResult()
}

func snapShotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.Raft_OperationsSnapShotArgs)
	realResult := result.(*api.Raft_OperationsSnapShotResult)
	success, err := handler.(api.Raft_Operations).SnapShot(ctx, realArg.Rep)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRaft_OperationsSnapShotArgs() interface{} {
	return api.NewRaft_OperationsSnapShotArgs()
}

func newRaft_OperationsSnapShotResult() interface{} {
	return api.NewRaft_OperationsSnapShotResult()
}

func pingpongtestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.Raft_OperationsPingpongtestArgs)
	realResult := result.(*api.Raft_OperationsPingpongtestResult)
	success, err := handler.(api.Raft_Operations).Pingpongtest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRaft_OperationsPingpongtestArgs() interface{} {
	return api.NewRaft_OperationsPingpongtestArgs()
}

func newRaft_OperationsPingpongtestResult() interface{} {
	return api.NewRaft_OperationsPingpongtestResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RequestVote(ctx context.Context, rep *api.RequestVoteArgs_) (r *api.RequestVoteReply, err error) {
	var _args api.Raft_OperationsRequestVoteArgs
	_args.Rep = rep
	var _result api.Raft_OperationsRequestVoteResult
	if err = p.c.Call(ctx, "RequestVote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AppendEntries(ctx context.Context, rep *api.AppendEntriesArgs_) (r *api.AppendEntriesReply, err error) {
	var _args api.Raft_OperationsAppendEntriesArgs
	_args.Rep = rep
	var _result api.Raft_OperationsAppendEntriesResult
	if err = p.c.Call(ctx, "AppendEntries", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SnapShot(ctx context.Context, rep *api.SnapShotArgs_) (r *api.SnapShotReply, err error) {
	var _args api.Raft_OperationsSnapShotArgs
	_args.Rep = rep
	var _result api.Raft_OperationsSnapShotResult
	if err = p.c.Call(ctx, "SnapShot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Pingpongtest(ctx context.Context, req *api.PingPongArgs_) (r *api.PingPongReply, err error) {
	var _args api.Raft_OperationsPingpongtestArgs
	_args.Req = req
	var _result api.Raft_OperationsPingpongtestResult
	if err = p.c.Call(ctx, "pingpongtest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
